[package]
name = "synapses"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", default-features = false }
bevy-trait-query = "0.5.1"
simulator = { path = "../simulator" }
neurons = { path = "../neurons" }
